_target_: src.datamodules.cifar_datamodule.CIFARDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 4
train_val_test_split: [50_000, 10_000]
num_workers: 0
pin_memory: False
